name: CJ CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.setvars.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set variables
        id: setvars
        run: |
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t cj-web:${IMAGE_TAG} .

      - name: Tag Docker image
        run: |
          docker tag cj-web:${IMAGE_TAG} ${ECR_REGISTRY}/cj-web:${IMAGE_TAG}
          docker tag cj-web:${IMAGE_TAG} ${ECR_REGISTRY}/cj-web:latest

      - name: Push to ECR
        run: |
          docker push ${ECR_REGISTRY}/cj-web:${IMAGE_TAG}
          docker push ${ECR_REGISTRY}/cj-web:latest

deploy:
  needs: build
  runs-on: ubuntu-latest

  steps:
    - name: Deploy to Kubernetes via SSH
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          kubectl set image deployment/cj-web \
          cj-web=101559246314.dkr.ecr.ap-southeast-2.amazonaws.com/cj-web:latest

          kubectl rollout status deployment/cj-web