name: CJ CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      ecr_registry: ${{ steps.set-vars.outputs.ecr_registry }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set variables
        id: set-vars
        run: |
          echo "IMAGE_TAG=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
          echo "ecr_registry=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t cj-web:${GITHUB_RUN_NUMBER} .

      - name: Tag Docker image
        run: |
          docker tag cj-web:${GITHUB_RUN_NUMBER} $ECR_REGISTRY/cj-web:${GITHUB_RUN_NUMBER}
          docker tag cj-web:${GITHUB_RUN_NUMBER} $ECR_REGISTRY/cj-web:latest

      - name: Push Docker image to ECR
        run: |
          docker push $ECR_REGISTRY/cj-web:${GITHUB_RUN_NUMBER}
          docker push $ECR_REGISTRY/cj-web:latest


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            export KUBECONFIG=/home/ec2-user/.kube/config

            kubectl set image deployment/cj-web \
              cj-web=${{ needs.build.outputs.ecr_registry }}/cj-web:latest

            kubectl rollout status deployment/cj-web